import { Open_Sans } from 'next/font/google'
import './globals.css'
import EnglishHeader from '@/components/English/Navbar/EnglishHeader'
import ArabicNavbar from '@/components/Arabic/Navbar/Arabicnavbar'
import { LanguageProvider } from '@/context/LanguageContext'


const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={openSans.className}>
       
       <LanguageProvider>
        <div>

        <EnglishHeader/>
        
        {/* <ArabicNavbar/> */}
        {children}
        </div>
        </LanguageProvider>
  
        </body>
    </html>
  )
}
